parameters:
#    hris_user.example.class: Hris\UserBundle\Example

services:
    admin.user:
        class: Hris\UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Users, label: Users }
        arguments: [ null, Hris\UserBundle\Entity\User, SonataAdminBundle:CRUD ]


    hris_user.menu_builder:
        class: Hris\UserBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    hris_user.menu.main:
        class: Knp\Menu\MenuItem #the service definition requires setting the class
        factory_service: hris_user.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: hris_menu } #The alias is what is used to retrieve menu