imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: doctrine_extensions.yml }
    - { resource: "@HrisUserBundle/Resources/config/profile.xml" }
    - { resource: "@HrisUserBundle/Resources/config/registration.xml" }
    - { resource: "@HrisUserBundle/Resources/config/group.xml" }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    exception_controller:  twig.controller.exception:showAction

    form:
        resources:
#            - ':Form:fields.html.twig'

    globals:
        # Place Global Variables here, and they will be available in all Twig Templetes.
            project: "Human Resource for Health Information System"
            project_code: "HRHIS"
            project_site: "https://github.com/hrisproject/hris"
            version: "3.0"
            copyright: "Human Resource Information System 2012"
            client_name: "Ministry of Health And Social Welfare"
            client_code: "MOHSW"

    cache:                     "%kernel.cache_dir%/twig"
    charset:                   "%kernel.charset%"
    debug:                     "%kernel.debug%"
    strict_variables:          "%kernel.debug%"

bc_bootstrap:
    less_filter: lessphp
    
# Assetic Configuration
assetic:
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        lessphp:
            file: "%kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php"
            apply_to: "\.less$"
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ FOSUserBundle  ]
    #java: /usr/bin/java

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
            translatable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
            loggable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
            tree:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"

# Swiftmailer Configuration
swiftmailer:
    transport: "gmail"
    username:  "hrismailer@gmail.com"
    password:  "hrismailer4testing"
    
# Monolog configuration
monolog:
    handlers:
        syslog:
            type: stream
            path: /var/log/symfony.log
            level: error
        main:
            type: fingers_crossed
            action_level: warning
            handler: file
        file:
            type: stream
            level: debug
#FOSUser Bundle configuration
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: secured_area
    user_class: Hris\UserBundle\Entity\User
    group:
        group_class: Hris\UserBundle\Entity\Group
    use_listener: true
    from_email:
        sender_name: "HRIS Mailer"
    registration:
        confirmation:
            from_email:
                sender_name: "HRIS Mailer"
            enabled: false
    resetting:
        email:
            from_email:
                sender_name: "HRIS Mailer"
#KnpMenuBundle Configurations
knp_menu:
   templating: false # if true, enables the helper for PHP templates
   default_renderer: twig # The renderer to use, list is also available by default
        
#SonataAdminBundle Configurations
sonata_admin:
#    security_handler: sonata.admin.security.handler.noop

    title:      Sonata Project
    title_logo: /bundles/sonataadmin/logo_title.png
    templates:
        # default global templates
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig
        dashboard: SonataAdminBundle:Core:dashboard.html.twig

        # default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig

    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }

            # Customize this part to add new block configuration
#            - { position: right, type: sonata.block.service.text, settings: { content: "<h2>Welcome to the Sonata Admin</h2> <p>This is a <code>sonata.block.service.text</code> from the Block Bundle, you can create and add new block in these area by configuring the <code>sonata_admin</code> section.</p> <br /> For instance, here a RSS feed parser (<code>sonata.block.service.rss</code>):"} }
#            - { position: right, type: sonata.block.service.rss, settings: { title: Sonata Project's Feeds, url: http://sonata-project.org/blog/archive.rss }}
        groups:
            default: ~
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:

# Tiny MCE configuration Bundle       
stfalcon_tinymce:
        include_jquery: true
        tinymce_jquery: true
        selector: ".tinymce"
        # Get current language from the parameters.ini
        language: %locale%
        # Custom buttons
        tinymce_buttons:
            stfalcon: # Id of the first button
                title: "Fields list"
                image: "asset[bundles/hrisform/img/list.ico]"
        external_plugins:
            filemanager7:
                url: "asset[js/bootstrap.js]"
            filemanager2:
                url: "asset[bundles/hrisform/js/field_selector.js]"

        theme:
            # Simple theme: same as default theme
            simple: ~
            # Advanced theme with almost all enabled plugins
            advanced:
                 content_css: "../../../commons/css/style.css"
                 plugins:
                     - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                     - "searchreplace wordcount visualblocks visualchars code fullscreen"
                     - "insertdatetime media nonbreaking save table contextmenu directionality"
                     - "emoticons template paste textcolor"
                 toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
                 toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example"
                 image_advtab: true
                 templates:
                     - {title: 'Test template 1', content: 'Test 1'}
                     - {title: 'Test template 2', content: 'Test 2'}
            # BBCode tag compatible theme (see http://www.bbcode.org/reference.php)
            bbcode:
                 plugins: ["bbcode, code, link, preview"]
                 menubar: false
                 toolbar1: "bold,italic,underline,undo,redo,link,unlink,removeformat,cleanup,code,preview"

jms_security_extra:
    # Whether you want to secure all services (true), or only secure specific
    # services (false); see also below
    secure_all_services: false

    # Enabling this setting will add an additional special attribute "ROLE_IDDQD".
    # Anybody with this attribute will effectively bypass all security checks.
    enable_iddqd_attribute: false

    # Enables expression language
    expressions: false

    # Allows you to disable some, or all built-in voters
    voters:
        disable_authenticated: false
        disable_role:          false
        disable_acl:           false

    # Allows you to specify access control rules for specific methods, such
    # as controller actions
    method_access_control: { }

fos_message:
    db_driver: orm
    thread_class: Hris\MessageBundle\Entity\Thread
    message_class: Hris\MessageBundle\Entity\Message
    new_thread_form:
          type:               fos_message.new_thread_multiple_form.type
          handler:            fos_message.new_thread_multiple_form.handler
          model:              FOS\MessageBundle\FormModel\NewThreadMultipleMessage
          name:               message
