imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    exception_controller:  twig.controller.exception:showAction
    form:
        resources:
            - "AcmeBundle:Form:form_div_layout.html.twig"    

    globals:
        # Place Global Variables here, and they will be available in all Twig Templetes.
            project: "%project%"
            version: "3.0"
            system_name: "HRHIS"
            copyright: "Ministry of Health and Social Welfare"
    
    cache:                     "%kernel.cache_dir%/twig"
    charset:                   "%kernel.charset%"
    debug:                     "%kernel.debug%"
    strict_variables:          "%kernel.debug%"
 
# Assetic Configuration
assetic:
    assets:
        bootstrap_css:
            inputs:
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/less/bootstrap.less"
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/less/responsive.less"
            filters:
                - less
                - cssrewrite
            output: css/bootstrap.css
        bootstrap_js:
            inputs:
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-transition.js"
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-alert.js"
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-button.js"
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-carousel.js"
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-collapse.js"
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-dropdown.js"
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-modal.js"
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-tooltip.js"
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-popover.js"
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-scrollspy.js"
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-tab.js"
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-typeahead.js"
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-affix.js"
            output: js/bootstrap.js
        jquery:
            inputs:
                - "%kernel.root_dir%/../vendor/jquery/jquery/jquery-1.10.0.js"
            output: js/jquery.js
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    
# Monolog configuration
monolog:
    handlers:
        syslog:
            type: stream
            path: /var/log/symfony.log
            level: error
        main:
            type: fingers_crossed
            action_level: warning
            handler: file
        file:
            type: stream
            level: debug
#FOSUser Bundle configuration
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main_firewall
    user_class: Hris\UserBundle\Entity\User
#KnpMenuBundle Configurations
knp_menu:
   twig:
       template: "AcmeBundle:Menu:menu.html.twig"
   templating: false # if true, enables the helper for PHP templates
   default_renderer: twig # The renderer to use, list is also available by default
        
#SonataAdminBundle Configurations
sonata_admin:
#    security_handler: sonata.admin.security.handler.noop

    title:      Sonata Project
    title_logo: /bundles/sonataadmin/logo_title.png
    templates:
        # default global templates
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig
        dashboard: SonataAdminBundle:Core:dashboard.html.twig

        # default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig

    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }

            # Customize this part to add new block configuration
#            - { position: right, type: sonata.block.service.text, settings: { content: "<h2>Welcome to the Sonata Admin</h2> <p>This is a <code>sonata.block.service.text</code> from the Block Bundle, you can create and add new block in these area by configuring the <code>sonata_admin</code> section.</p> <br /> For instance, here a RSS feed parser (<code>sonata.block.service.rss</code>):"} }
#            - { position: right, type: sonata.block.service.rss, settings: { title: Sonata Project's Feeds, url: http://sonata-project.org/blog/archive.rss }}
        groups:
            default: ~
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:
bc_bootstrap:
    assets_dir:  "%kernel.root_dir%/../vendor/twitter/bootstrap"
    jquery_path: "%kernel.root_dir%/../vendor/jquery/jquery/jquery-1.10.0.js"
